version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "your user"
      POSTGRES_PASSWORD: "your pwd"
      PGDATA: /data/postgres
    volumes:
       - "$PWD/postgres:/data/postgres"
    ports:
      - "5432:5432"
    networks:
      - bd-network
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "your email"
      PGADMIN_DEFAULT_PASSWORD: "your pwd"
      #PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - "$PWD/pgadmin:/var/lib/pgadmin"
    ports:
      - "16543:80"
    networks:
      - bd-network
    restart: always

  sql2017:
    container_name: sql2017
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "your pwd"
    ports:
      - "41433:1433"
    volumes:
      - "$PWD/SQLServer2017:/var/opt/mssql"
    networks:
      - bd-network

  sql2019:
    container_name: sql2019
    image: mcr.microsoft.com/mssql/server:2019-GDR1-ubuntu-16.04
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "your pwd!"
    ports:
      - "41434:1433"
    volumes:
      - "$PWD/SQLServer2019:/var/opt/mssql"
    networks:
      - bd-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 19081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "your user"
      ME_CONFIG_BASICAUTH_PASSWORD: "your pwd!"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "your user"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "your pwd"
    links:
      - mongo
    networks:
      - bd-network

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "your user"
      MONGO_INITDB_ROOT_PASSWORD: "your pwd"
    ports:
      - "37017:27017"
    volumes:
      - "$PWD/MongoDB:/data/db"
    networks:
      - bd-network    
  mysql:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      #MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: "your user"
      MYSQL_PASSWORD: "your pwd'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - "$PWD/mysql8/db/data:/var/lib/mysql"
      - "$PWD/mysql8/db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "$PWD/mysql8/db/sql:/docker-entrypoint-initdb.d"
networks:
  bd-network:
    driver: bridge

#volumes:
#    postgres:
#    pgadmin:
